<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Satish-PC" ignored="0" name="retryFailedTTestCases" tests="9" failures="2" timestamp="01 Aug 2019 08:54:38 GMT" time="0.142" errors="0">
  <testcase name="Test1" time="0.018" classname="ReTestFailedTests.mytests">
    <skipped/>
  </testcase> <!-- Test1 -->
  <testcase name="Test1" time="0.002" classname="ReTestFailedTests.mytests">
    <skipped/>
  </testcase> <!-- Test1 -->
  <testcase name="Test1" time="0.001" classname="ReTestFailedTests.mytests">
    <skipped/>
  </testcase> <!-- Test1 -->
  <testcase name="Test1" time="0.001" classname="ReTestFailedTests.mytests">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]at ReTestFailedTests.mytests.Test1(mytests.java:11)... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- Test1 -->
  <testcase name="Test2" time="0.002" classname="ReTestFailedTests.mytests">
    <skipped/>
  </testcase> <!-- Test2 -->
  <testcase name="Test2" time="0.002" classname="ReTestFailedTests.mytests">
    <skipped/>
  </testcase> <!-- Test2 -->
  <testcase name="Test2" time="0.001" classname="ReTestFailedTests.mytests">
    <skipped/>
  </testcase> <!-- Test2 -->
  <testcase name="Test2" time="0.014" classname="ReTestFailedTests.mytests">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]at ReTestFailedTests.mytests.Test2(mytests.java:17)... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- Test2 -->
  <testcase name="Test3" time="0.002" classname="ReTestFailedTests.mytests"/>
</testsuite> <!-- retryFailedTTestCases -->
