<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="Satish-PC" name="TestNg.ExceptionTimeOutTest" tests="2" failures="0" timestamp="25 May 2019 07:20:38 GMT" time="0.025" errors="1">
  <testcase name="infiniteLoop" time="0.023" classname="TestNg.ExceptionTimeOutTest">
    <error type="org.testng.internal.thread.ThreadTimeoutException" message="Method TestNg.ExceptionTimeOutTest.infiniteLoop() didn&#039;t finish within the time-out 10">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method TestNg.ExceptionTimeOutTest.infiniteLoop() didn't finish within the time-out 10at java.io.FileOutputStream.writeBytes(Native Method)at java.io.FileOutputStream.write(FileOutputStream.java:326)at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140)at java.io.PrintStream.write(PrintStream.java:482)at sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:221)at sun.nio.cs.StreamEncoder.implFlushBuffer(StreamEncoder.java:291)at sun.nio.cs.StreamEncoder.flushBuffer(StreamEncoder.java:104)at java.io.OutputStreamWriter.flushBuffer(OutputStreamWriter.java:185)at java.io.PrintStream.write(PrintStream.java:527)at java.io.PrintStream.print(PrintStream.java:669)at java.io.PrintStream.println(PrintStream.java:806)at TestNg.ExceptionTimeOutTest.infiniteLoop(ExceptionTimeOutTest.java:13)at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)at java.lang.reflect.Method.invoke(Method.java:498)at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:40)at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)at java.util.concurrent.FutureTask.run(FutureTask.java:266)at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)at java.lang.Thread.run(Thread.java:748)]]>
    </error>
  </testcase> <!-- infiniteLoop -->
  <testcase name="test" time="0.002" classname="TestNg.ExceptionTimeOutTest"/>
</testsuite> <!-- TestNg.ExceptionTimeOutTest -->
